# Find your Client ID & Client Secret at
# https://www.strava.com//settings/api
client_id: 11111
client_secret: a1b2c3d4e5f6g7h8i9j10k11l12m13n14o15p16

# Configuration variables, more info at
#
special_char: "!"
name_format:
  "{{ activity.type }} {% if end_location.amenity %} to {{ end_location.amenity}}{%
  else %}near {{ end_location.suburb }} {% endif %}"
des_format:
  "A {{ (weather.temp - 273.15)|round(2) }} \xB0C day, with max speed of\
  \ {{ (activity.max_speed * 3.6)|round(2) }} km/h"

# Create one at
# https://openweathermap.org/api
weather_api: a1b2c3d4e5f6g7h8i9j10k11l12m13n14o15p16
